import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import styles from './index.module.css';
const highlights=[{value:'5+',label:'upstream pull requests'},{value:'3',label:'merged contributions'},{value:'GSoC 26',label:'Metasploit contributor'}];
const work=[{number:21466,title:'Kerberos ticket tracing',text:'Operator-readable visibility into AS, TGS and credential flows.',status:'Merged'},{number:21638,title:'Offline ticket inspection',text:'One trace language for live authentication and stored Kerberos artifacts.',status:'Merged'},{number:21637,title:'Purposeful trace modes',text:'Metadata, ticket and full modes balance clarity with sensitive output.',status:'Merged'}];
export default function Home():React.JSX.Element{return <Layout title="Cyan - GSoC 2026" description="Cyan's GSoC 2026 journey with Metasploit"><main>
<section className={styles.hero}><div className={styles.glow}/><div className={styles.heroInner}><div className={styles.eyebrow}><span/> GOOGLE SUMMER OF CODE 2026</div><h1>Tracing what Kerberos<br/><em>usually keeps hidden.</em></h1><p className={styles.lead}>Hi, I am Cyan - an open-source developer building Kerberos observability for the Metasploit Framework.</p><div className={styles.actions}><Link className={styles.primary} to="/gsoc">Explore the project <span aria-hidden="true">&#8599;</span></Link><a className={styles.secondary} href="https://github.com/eve0805">GitHub profile <span aria-hidden="true">&#8594;</span></a></div><div className={styles.stats}>{highlights.map(x=><div key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</div></div>
<div className={styles.terminal}><div className={styles.terminalBar}><i/><i/><i/><span>kerberos.trace</span></div><pre><span className={styles.muted}>$</span> set KerberosTicketTrace metadata{`\n`}<span className={styles.green}>[+]</span> AS-REQ  <span className={styles.muted}>client</span> cyan@LAB.LOCAL{`\n`}<span className={styles.green}>[in]</span> AS-REP  <span className={styles.muted}>etype</span> aes256{`\n`}<span className={styles.blue}>[out]</span> TGS-REQ <span className={styles.muted}>service</span> cifs/dc01{`\n`}<span className={styles.green}>[in]</span> TGS-REP <span className={styles.muted}>status</span> success{`\n`}{`\n`}<span className={styles.cursor}>_</span></pre></div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.kicker}>SELECTED WORK</span><h2>Upstream, one layer at a time.</h2></div><Link to="/contributions">View all contributions &#8594;</Link></div><div className={styles.workGrid}>{work.map((x,i)=><a className={styles.workCard} key={x.number} href={`https://github.com/rapid7/metasploit-framework/pull/${x.number}`}><div><span className={styles.index}>0{i+1}</span><span className={styles.badge}>{x.status}</span></div><h3>{x.title}</h3><p>{x.text}</p><footer><code>rapid7/metasploit-framework #{x.number}</code><span>&#8599;</span></footer></a>)}</div></section>
<section className={styles.about}><div><span className={styles.kicker}>ABOUT THE WORK</span><h2>Make complex protocol flows readable.</h2></div><div><p>Kerberos failures are often buried beneath encryption, protocol wrappers and several authentication stages. My GSoC work adds a shared tracing foundation that helps operators understand what happened - during live authentication, offline inspection and ticket forging.</p><Link to="/gsoc">Read the project overview <span>&#8594;</span></Link></div></section>
</main></Layout>}
